#!/usr/bin/env bash
# Tonum Wallet — test run on your own Mac (no server or domain needed).
#   bash deploy/mac-test.sh
# Starts PostgreSQL and the app in Docker Desktop and opens a free Cloudflare quick tunnel
# (https://….trycloudflare.com), so Telegram can open the Mini App from your phone.
# The tunnel address changes on every start; the bot picks up the new one automatically.
# Keep the Terminal window open while testing; press Ctrl+C to stop.
set -euo pipefail

cd "$(dirname "$0")/.."

bold() { printf '\n\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '\033[32m✔ %s\033[0m\n' "$*"; }
warn() { printf '\033[33m! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

COMPOSE=(docker compose -f docker-compose.yml -f deploy/docker-compose.local.yml)

get_env() { [ -f .env ] && grep -E "^$1=" .env | head -1 | cut -d= -f2- || true; }

ask() { # ask "Вопрос" regex [secret]
  local prompt="$1" re="$2" secret="${3:-}" value
  while true; do
    if [ -n "$secret" ]; then
      read -r -s -p "$prompt: " value </dev/tty; echo >&2
    else
      read -r -p "$prompt: " value </dev/tty
    fi
    value="$(printf '%s' "$value" | tr -d '[:space:]')"
    if [[ "$value" =~ $re ]]; then printf '%s' "$value"; return; fi
    warn "Похоже, значение введено неверно. Попробуйте ещё раз."
  done
}

bold "1/4  Docker"
command -v docker >/dev/null 2>&1 ||
  die "Docker не найден. Установите Docker Desktop (https://www.docker.com/products/docker-desktop/), откройте его и запустите скрипт снова."
docker info >/dev/null 2>&1 ||
  die "Docker Desktop не запущен. Откройте его, подождите ~30 секунд и запустите скрипт снова."
ok "Docker работает"

bold "2/4  Ключи"
bot_token="$(get_env BOT_TOKEN)"
cp_token="$(get_env CRYPTOPAY_TOKEN)"
if [ -z "$bot_token" ] || [ -z "$cp_token" ]; then
  echo "Ключи вводятся скрыто — при вставке символы не отображаются, это нормально."
fi
[ -n "$bot_token" ] || bot_token="$(ask "Ключ бота от @BotFather" '^[0-9]+:[A-Za-z0-9_-]{30,}$' secret)"
[ -n "$cp_token" ] || cp_token="$(ask "Ключ Crypto Pay из @CryptoTestnetBot" '^[0-9]+:[A-Za-z0-9_-]+$' secret)"
network="$(get_env CRYPTOPAY_NETWORK)"; [ -n "$network" ] || network=testnet
pg_pass="$(get_env POSTGRES_PASSWORD)"; [ -n "$pg_pass" ] || pg_pass="$(openssl rand -hex 24)"
ok "Ключи на месте (сохраняются в файле .env — повторно вводить не нужно)"

bold "3/4  Туннель в интернет"
cf="$(command -v cloudflared || true)"
if [ -z "$cf" ]; then
  cf=.bin/cloudflared
  if [ ! -x "$cf" ]; then
    case "$(uname -m)" in arm64 | aarch64) arch=arm64 ;; *) arch=amd64 ;; esac
    base=https://github.com/cloudflare/cloudflared/releases/latest/download
    mkdir -p .bin
    echo "Скачиваем cloudflared (~20 МБ, один раз)…"
    if [ "$(uname -s)" = Darwin ]; then
      curl -fL --progress-bar -o .bin/cloudflared.tgz "$base/cloudflared-darwin-$arch.tgz"
      tar -xzf .bin/cloudflared.tgz -C .bin && rm -f .bin/cloudflared.tgz
    else
      curl -fL --progress-bar -o "$cf" "$base/cloudflared-linux-$arch"
    fi
    chmod +x "$cf"
  fi
fi

rm -f .tunnel.log
"$cf" tunnel --no-autoupdate --url http://localhost:3000 >.tunnel.log 2>&1 &
cf_pid=$!

cleanup() {
  trap - INT TERM EXIT
  echo
  echo "Останавливаем…"
  kill "$cf_pid" 2>/dev/null || true
  "${COMPOSE[@]}" stop >/dev/null 2>&1 || true
  echo "Остановлено. Запустить снова: bash deploy/mac-test.sh"
}
trap cleanup INT TERM EXIT

url=""
for _ in $(seq 1 60); do
  url="$(grep -oE 'https://[-a-z0-9]+\.trycloudflare\.com' .tunnel.log | grep -v '//api\.' | head -1 || true)"
  [ -n "$url" ] && break
  kill -0 "$cf_pid" 2>/dev/null || { tail -20 .tunnel.log >&2; die "Туннель не запустился (журнал выше)"; }
  sleep 1
done
[ -n "$url" ] || { tail -20 .tunnel.log >&2; die "Не удалось получить адрес туннеля. Проверьте интернет и попробуйте снова."; }
ok "Адрес: $url"

umask 077
cat >.env <<ENV
# Generated by deploy/mac-test.sh for testing on this computer.
NODE_ENV=production
TRUST_PROXY=true
LOG_LEVEL=info

POSTGRES_PASSWORD=$pg_pass

BOT_TOKEN=$bot_token
BOT_MODE=polling
PUBLIC_URL=$url
WEBAPP_URL=$url

PAYMENT_PROVIDER=cryptopay
CRYPTOPAY_TOKEN=$cp_token
CRYPTOPAY_NETWORK=$network
ASSETS=USDT,TON
ENV

bold "4/4  Сборка и запуск (первый раз — 3–7 минут)"
"${COMPOSE[@]}" up -d db
"${COMPOSE[@]}" up -d --build --force-recreate app

printf 'Ждём запуска'
started=no
for _ in $(seq 1 100); do
  if curl -fsS --max-time 2 http://localhost:3000/api/health >/dev/null 2>&1; then started=yes; break; fi
  printf '.'; sleep 3
done
echo
if [ "$started" != yes ]; then
  warn "Приложение не отвечает. Последние строки журнала:"
  "${COMPOSE[@]}" logs --tail 40 app >&2 || true
  exit 1
fi
ok "Приложение запущено"

for _ in $(seq 1 20); do
  curl -fsS --max-time 5 "$url/api/health" >/dev/null 2>&1 && break
  sleep 2
done

bold "Готово! Можно тестировать в Telegram:"
cat <<TXT

  1) Откройте своего бота в Telegram и отправьте /start
  2) Нажмите «Открыть Tonum Wallet» (или кнопку «Tonum Wallet» слева от поля ввода)

  Деньги тестовые: платите и получайте выводы в @CryptoTestnetBot.
  Пополнение зачисляется в течение ~30 секунд после оплаты.
  Для выводов включите в Crypto Pay переводы (Transfers) и пополните баланс приложения.

  Пока идёт тест, не закрывайте это окно и не давайте Mac уснуть (держите крышку открытой).
  Остановить — Ctrl+C. Журнал приложения — в новом окне: docker compose logs -f app
TXT

# Keep running until the tunnel exits or the user presses Ctrl+C.
wait "$cf_pid" || true
warn "Туннель остановился. Запустите скрипт снова: bash deploy/mac-test.sh"
